export const ROUTES = {
  BUTTONS: "/buttons",
  CARDS: "/cards",
  NAVIGATION: "/navigation",
  FORMS: "/forms",
  MODALS: "/modals",
  TABLES: "/tables",
  COLORS: "/colors",
  BORDERS: "/borders",
  TYPOGRAPHY: "/typography",
  ICONS: "/icons",
  GRID: "/grid",
  FLEXBOX: "/flexbox",
  SPACING: "/spacing",
  LOGIN: "/login",
  DASHBOARDS: "/dashboards",
  LANDING: "/landing",
  ECOMMERCE: "/ecommerce",
};

export const COMPONENT_TYPES = {
  BUTTONS: "buttons",
  CARDS: "cards",
  NAVIGATION: "navigation",
  FORMS: "forms",
  MODALS: "modals",
  TABLES: "tables",
  COLORS: "colors",
  BORDERS: "borders",
  TYPOGRAPHY: "typography",
  ICONS: "icons",
  GRID: "grid",
  FLEXBOX: "flexbox",
  SPACING: "spacing",
  LOGIN: "login",
  DASHBOARDS: "dashboards",
  LANDING: "landing",
  ECOMMERCE: "ecommerce",
};
